

name: 'dbt_course_july'
version: '1.0.0'

profile: 'dbt_course_july'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


seeds:
  +schema: "public"


models:
  dbt_course_july:
    +materialized: table
    +schema: public
    example:
      +materialized: table
